import accelerationVector from "./lessons/accelerationVector";
import dragForce from "./lessons/dragForce";
import friction from "./lessons/friction";
import gravitationalAttraction from "./lessons/gravitationalAttraction";
import lesson1 from "./lessons/lesson1";
import lesson2 from "./lessons/lesson2";
import mutualAttraction from "./lessons/mutualAttraction";
import randomWalker from "./lessons/randomWalker";
import test from "./lessons/test";
import angleMotiion from "./lessons/angleMotiion";
import gravitationalAttractionWithAngle from "./lessons/ossillation/gravitationalAttractionWithAngle";
import directionPoint from "./lessons/directionPoint";
import spaceShip from "./lessons/ossillation/spaceShip";
import polarCoor from "./lessons/ossillation/polarCoor";
import sineWave from "./lessons/ossillation/sineWaveWithPeriod";
import graphWave from "./lessons/ossillation/graphWave";
// randomWalker();
// gravitationalAttraction();
// directionPoint();
// polarCoor();
graphWave();
